title: "My Website"
description: "A description of my site"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# Optional: Customize navigation links
nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/

# Optional: Social links
author:
  name: Your Name
  social:
    twitter: your_twitter_handle
    github: your_github_username
