title: "My Site Title"
description: "A description of my site."
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# Optional: Customize navigation links
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
